version: '3.8'

services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: flowdocs
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD}  # Set as Dokploy secret
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  web:
    build: .   # Dokploy builds from Dockerfile in repo
    command: gunicorn --bind 0.0.0.0:8000 --workers 3 flowdocs.wsgi:application
    ports:
      - "8000:8000"
    environment:
      DEBUG: "False"
      DB_NAME: flowdocs
      DB_USER: postgres
      DB_PASSWORD: ${DB_PASSWORD}  # Dokploy secret
      DB_HOST: db
      DB_PORT: 5432
      REDIS_URL: redis://redis:6379/1
      SECRET_KEY: ${SECRET_KEY}    # Dokploy secret
    depends_on:
      - db
      - redis
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media

volumes:
  postgres_data:
  static_volume:
  media_volume:
