web:
  image: prod-frontend-aywco9:latest
  command: gunicorn --bind 0.0.0.0:8000 --workers 3 flowdocs.wsgi:application
  ports:
    - "8000:8000"
  environment:
    DEBUG: "False"
    DB_NAME: flowdocs
    DB_USER: postgres
    DB_PASSWORD: ${DB_PASSWORD}
    DB_HOST: db
    DB_PORT: 5432
    REDIS_URL: redis://redis:6379/1
    SECRET_KEY: ${SECRET_KEY}
  depends_on:
    - db
    - redis
  volumes:
    - static_volume:/app/staticfiles
    - media_volume:/app/media
