# Generated by Django 4.2.23 on 2025-09-03 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_pdffile_content_pdffile_search_vector_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='pdffile',
            name='core_pdffil_search__1650a6_gin',
        ),
        migrations.RemoveField(
            model_name='pdffile',
            name='content',
        ),
        migrations.RemoveField(
            model_name='pdffile',
            name='search_vector',
        ),
        migrations.AddField(
            model_name='pdffile',
            name='text_content',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='pdffile',
            name='keywords',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
