global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # AI Document Search Application
  - job_name: 'ai-document-search'
    static_configs:
      - targets: ['host.docker.internal:8000']  # Adjust based on your setup
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s

  # Jaeger
  - job_name: 'jaeger'
    static_configs:
      - targets: ['jaeger:14269']

  # Redis
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']

  # Node Exporter (if available)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 30s
